# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - uses: actions/checkout@v2
      - name: Run on architecture
  # You may pin to the exact commit or the version.
  # uses: uraimo/run-on-arch-action@e24ce273595f4dfa6572e9a406d87b249a7bb47c
        uses: darsvador/run-on-arch-action@v1.0.10
        with:
    # CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.
          architecture: armv7
    # Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, bullseye, buster, stretch, jessie, fedora_latest, alpine_latest, archarm_latest.
    # Shell commands to execute in the container.
          run: python3 setup.py install
    # The shell to run commands with in the container. Default: /bin/sh on alpine (because Alpine uses BusyBox), /bin/bash for other distros
